name: auto_inject_dev
description: Code generator for automatic dependency injection
homepage: https://github.com/LeFrosch/auto-inject-ii

version: 0.0.3

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  auto_inject: ^0.0.3

  analyzer: ^5.13.0
  build: ^2.3.1

  code_builder: ^4.3.0
  source_gen: ^1.2.5

  glob: ^2.1.0
  equatable: ^2.0.5
  collection: ^1.16.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0

  build_test: ^2.1.5
  build_resolvers: ^2.0.10
