name: auto_inject
description: Annotation library for automatic dependency injection
homepage: https://github.com/LeFrosch/auto-inject-ii

version: 0.0.4

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  get_it: ^7.6.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
